cmake: windows compiler doesn't support variable length arrays
This is error C2057 for the constant expression

  build\_deps\openv2g-src\src\codec\EncoderChannel.c(239,39): \
    error C2057: expected constant expression
  build\_deps\openv2g-src\src\codec\EncoderChannel.c(239,39): \
    error C2057:         uint8_t bytesToShift[MAX_BIGINT_ARRAY]; // MAXIMUM

So, this is bit of restructure to patch the openv2g twice to get
the compile to work - will patch all builds with the windows fix
as well since it should work on all platforms.

Signed-off-by: Charles Hardin <charles.hardin@chargepoint.com>